version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - jq --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=922334818590.dkr.ecr.us-east-1.amazonaws.com/ocrion-aws-be-pr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing definitions file...
      - printf '[{"name":"ocrion-aws-be-pr","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > taskdefinition.json
      - zip taskdefinition.zip taskdefinition.json
      - aws s3 cp taskdefinition.zip s3://ocrion-task-definitions/taskdefinition.zip
artifacts:
    files: taskdefinition.json
